fix(a11y): make focus ring meet 3:1 requirements
StackExchange/Stacks pull request #1547
Opened 2023-10-27 18:39 UTC by dancormier

This PR modifies the focus ring we use on focused elements to meet or exceed [WCAG 2.2 Success Criterion 2.4.11: Focus Appearance (Minimum)](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum)

> Success Criterion [2.4.11 Focus Appearance (Minimum)](https://www.w3.org/TR/WCAG22/#focus-appearance-minimum) (Level AA): When a [user interface component](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum#dfn-user-interface-component) has keyboard focus, the [focus indicator](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum#dfn-focus-indicator):
>
>   - [Encloses](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum#dfn-encloses) the visual presentation of the user interface component;
>   - Has a contrast ratio of at least 3:1 between its pixels in the focused and unfocused states;
>   - Has a contrast ratio of at least 3:1 against adjacent colors.
>
>    Exceptions:
>
>    - The focus indicator is determined by the user-agent and cannot be adjusted by the author, or
>    - The focus indicator and the indicator's background color are not modified by the author, or
>    - An area of the focus indicator meets all the following:
>        - At least as large as the area of a 1 [CSS pixel](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum#dfn-css-pixel) thick [perimeter](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum#dfn-perimeter) of the unfocused component, or is at least as large as a 4 CSS pixel thick line along the shortest side of the [minimum bounding box](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum#dfn-minimum-bounding-box) of the unfocused component, and
>        - has a contrast ratio of at least 3:1 against the same pixels in the unfocused state, and
>        - has a contrast ratio of at least 3:1 against adjacent non-focus-indicator colors, or is no thinner than 2 CSS pixels.
>
>    Where a user interface component has active sub-components, if a sub-component receives a focus indicator, these requirements can be applied to the sub-component instead.
>
>    Note: Examples of sub-components that may receive a focus indicator are menu items in an opened drop-down menu. However, it may also be possible to indicate user interaction for such sub-components by relying strictly on a visual indication of which item is selected. Where selectable sub-components have no differentiated focus indicator, the visual indicator for sub-component selection is measured against [1.4.11 Non-text Contrast](https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast.html) requirements, not against this Criterion.
>
>    Note: Contrast calculations can be based on colors defined within the technology (such as HTML, CSS and SVG). Pixels modified by user agent resolution enhancements and anti-aliasing can be ignored.

### Questions

- Should we retain the `muted` version of the focus ring or replace it with the default?
- Which components need focus rings added?

### Notes

- I added focus rings to both `pagination` and `tags` but I'm not sure they need custom focus rings.

cc @CGuindon @andrewmeacham

2023-10-27 19:49 UTC, CGuindon commented
@dancormier 

> Should we retain the muted version of the focus ring or replace it with the default?

I think you left Muted (keeping the grey) but bumped it up to use stop 500 as well... so would that always show up as grey on themes or is it pulling from a theme color?

2023-10-27 19:50 UTC, CGuindon requested changes
Just started looking quickly and noticed we might have to add the extra outline to a few other elements like the nav items:

<img width="529" alt="Screenshot 2023-10-27 at 12 46 55 PM" src="https://github.com/StackExchange/Stacks/assets/5436760/da0a7a50-1200-439c-a65a-1119dd398290">

2023-10-27 19:51 UTC, CGuindon commented
> Which components need focus rings added?

Just finished getting through everything mentioned specifically in the bug sheet + a few others I noticed. Everything we need to add the focus-ring class to should be in the ticket now. I can start helping with this on Monday. I'm going to wrap up a few things on the Cprod side for the rest of the afternoon and then come back to this fresh next week.

2023-10-27 21:35 UTC, dancormier commented
> @dancormier
> 
> > Should we retain the muted version of the focus ring or replace it with the default?
> 
> I think you left Muted (keeping the grey) but bumped it up to use stop 500 as well... so would that always show up as grey on themes or is it pulling from a theme color?

Originally, I kept it around with `black-500` as the color. I removed it in https://github.com/StackExchange/Stacks/pull/1547/commits/4c6048a93f955b6900769664ca1688e90bc5f0ee base on this from the ticket:

> The focus muted state should no longer be used — move to have everything use focus default

@CGuindon Still good on removing it or would you like to keep it as `black-500` (or another color)?

2023-10-27 21:37 UTC, dancormier commented
> Just started looking quickly and noticed we might have to add the extra outline to a few other elements like the nav items:
> <img alt="Screenshot 2023-10-27 at 12 46 55 PM" width="529" src="https://user-images.githubusercontent.com/5436760/278745469-da0a7a50-1200-439c-a65a-1119dd398290.png">

The topbar had some focus overrides that affected `s-navigation`. I removed those overrides in [this commit](https://github.com/StackExchange/Stacks/pull/1547/commits/402bf1c21b220e3e6e514b6a0f5519aa727be79e), so it should be all good

2023-10-30 15:20 UTC, CGuindon commented
@dancormier Let's keep muted style for now — I think we're ok leaving it since it also got bumped to use black-500. I'll take a look through the PR.

2023-10-30 20:10 UTC, CGuindon requested changes
(testing on deploy preview)

Not sure if this is just in Stacks or will apply to the sites as well but I would make everything in the top bar use the default focus ring (vs some using default and some using muted). I _think_ everything should be blue up top if it gets switched to default. I don't mind the orange outline as much but I don't think we need to be adding another additional color. (default:theme blue, muted: grey and then the warning ones).

What determines it using the orange instead of the blue? tied to the background color somehow?

<img width="499" alt="Screenshot 2023-10-30 at 12 58 58 PM" src="https://github.com/StackExchange/Stacks/assets/5436760/1a9ae84a-fbba-497c-9e99-7c7014d241c6">
 
<img width="169" alt="Screenshot 2023-10-30 at 12 59 03 PM" src="https://github.com/StackExchange/Stacks/assets/5436760/15449297-82c5-45b6-a1b8-3ecf9183e897">

<img width="321" alt="Screenshot 2023-10-30 at 12 58 42 PM" src="https://github.com/StackExchange/Stacks/assets/5436760/908c1142-b633-4e62-9452-17b659a857c7">

2023-10-30 20:27 UTC, CGuindon commented
The `? icon` in the text editor seems to have some transparency compared to the other icons in there so it's appearing lighter than blue-500. 
<img width="106" alt="Screenshot 2023-10-30 at 1 25 12 PM" src="https://github.com/StackExchange/Stacks/assets/5436760/6f237f3c-de67-44aa-b623-ac4a2e4a214c">

2023-10-30 20:31 UTC, CGuindon commented
In stacks today (focus on tag):
<img width="293" alt="Screenshot 2023-10-30 at 1 29 20 PM" src="https://github.com/StackExchange/Stacks/assets/5436760/cc9b2a6b-5f95-4238-bea3-d1076dc96c4f">

In the deploy-preview (focus on tag):
<img width="383" alt="Screenshot 2023-10-30 at 1 28 25 PM" src="https://github.com/StackExchange/Stacks/assets/5436760/8b707658-8061-4779-8e9b-85ed43d9c0c1">

There's a difference happening with the hover and focus state of tags with the X icon. It seems that I can't hover/select/focus the tag itself when the icon is present, I can only focus on the X icon. So this would mean you couldn't link to the tag page when this is used, you'd only be able to remove the tag — which is a change from what we have today I think.

2023-10-30 20:51 UTC, dancormier commented
> The ? icon in the text editor seems to have some transparency compared to the other icons in there so it's appearing lighter than blue-500.

@CGuindon In the Stacks docs, that button is _styled as_ disabled. It really shouldn't be focusable at all. I have a [PR on the Stacks-Editor](https://github.com/StackExchange/Stacks-Editor/pull/260) to address this issue.

---

> In stacks today (focus on tag): <img alt="Screenshot 2023-10-30 at 1 29 20 PM" width="293" src="https://user-images.githubusercontent.com/5436760/279186940-cc9b2a6b-5f95-4238-bea3-d1076dc96c4f.png">
> 
> In the deploy-preview (focus on tag): <img alt="Screenshot 2023-10-30 at 1 28 25 PM" width="383" src="https://user-images.githubusercontent.com/5436760/279187069-8b707658-8061-4779-8e9b-85ed43d9c0c1.png">
> 
> There's a difference happening with the hover and focus state of tags with the X icon. It seems that I can't hover/select/focus the tag itself when the icon is present, I can only focus on the X icon. So this would mean you couldn't link to the tag page when this is used, you'd only be able to remove the tag — which is a change from what we have today I think.

What your seeing here is an update to the docs to replace invalid HTML. I added some clarification to the PR description:

> Changed tag documentation to use `span` when example includes a nested button
>    - This was changed from the `.s-tag` being an anchor with a nested `span` for `.s-tag--dismiss`. Since `.s-tag--dismiss` is expected to always be interactive, it should be rendered as a `button` element, which cannot be placed within an anchor element.  From [W3C "`a` Additional constraints and admonitions"](https://w3c.github.io/html-reference/a.html#a-constraints):
>        > The interactive element `a` must not appear as a descendant of the `button` element. 

It has no material effect on consumers of tag. It's really just a docs change (that should be implemented in Core, but that's another story)

2023-10-30 21:05 UTC, dancormier commented
> (testing on deploy preview)
> 
> Not sure if this is just in Stacks or will apply to the sites as well but I would make everything in the top bar use the default focus ring (vs some using default and some using muted). I _think_ everything should be blue up top if it gets switched to default. I don't mind the orange outline as much but I don't think we need to be adding another additional color. (default:theme blue, muted: grey and then the warning ones).
> 
> What determines it using the orange instead of the blue? tied to the background color somehow?
> <img alt="Screenshot 2023-10-30 at 12 58 58 PM" width="499" src="https://user-images.githubusercontent.com/5436760/279182849-1a9ae84a-fbba-497c-9e99-7c7014d241c6.png"> <img alt="Screenshot 2023-10-30 at 12 59 03 PM" width="169" src="https://user-images.githubusercontent.com/5436760/279182850-15449297-82c5-45b6-a1b8-3ecf9183e897.png"> <img alt="Screenshot 2023-10-30 at 12 58 42 PM" width="321" src="https://user-images.githubusercontent.com/5436760/279182842-908c1142-b633-4e62-9452-17b659a857c7.png">

## Muted focus ring in topbar

There's two elements that get that the muted focus ring in the topbar are "navigation" items and the muted buttons.

### Navigation

I haven't modified how the [navigation component](https://deploy-preview-1547--stacks.netlify.app/product/components/navigation/) focus states look in general, so they've retained the muted focus ring. It's focus ring style is unmodified in the context of the topbar.

### Muted button

Same with the [muted button](https://deploy-preview-1547--stacks.netlify.app/product/components/buttons/#muted). In the topbar, buttons get whichever focus ring style they normally have. This is proabably only an issue in the main topbar in the Stack docs pages since we don't generally stick muted buttons up there.

### Possible solution

I figure there's a few ways to address this:

#### Add topbar-specific overrides

We could set the focus ring color for those elements within the context of the topbar. I'm not a huge fan of this idea since we could wind up playing whack-a-mole since we can't always guarantee what elements could be shoved into the topbar.

#### Remove the muted focus ring in favor of the default style

We _almost_ removed the muted focus ring style. If we want muted elements to use the default focus ring style, replacing the muted style is one option.

#### Use the default focus ring style on navigation items

Navigation items use muted but could be switched to use the default focus ring. This wouldn't address the muted button in the header issue though.

## The orange outline

> I don't mind the orange outline as much

@CGuindon Some themed elements get a matching themed outline currently (navigation may be the only one that gets the "primary" theme color by default). Do you want to change this so that it gets the secondary color for the focus ring to match up with most other components?

2023-10-30 23:41 UTC, CGuindon commented
@dancormier 

> Navigation items use muted but could be switched to use the default focus ring. This wouldn't address the muted button in the header issue though.

I'm tempted to go this route, do you recall the reasoning behind why an element should get default vs muted? I think if buttons have default than nav items should as well?

> Do you want to change this so that it gets the secondary color for the focus ring to match up with most other components

Let's leave this as is.

2024-01-30 23:16 UTC, closed without merging