add s-list__horizontal and docs
StackExchange/Stacks pull request #559
Opened 2020-12-03 20:10 UTC by benjamin-hodgson

2020-12-03 20:27 UTC, benjamin-hodgson commented on lib/css/components/_stacks-lists.less
> +    > li:not(:last-child)::after {
@aaronshekey Do you prefer `:not(:last-child)::after` or `:not(:first-child)::before` for the bullets? It'd affect text styling applied to the `li`s and also the wrapping behaviour when it goes to a second line

2020-12-03 20:31 UTC, benjamin-hodgson commented on lib/css/components/_stacks-lists.less
> +        margin: 0 @su2;
@aaronshekey I suppose we'll need a way to control the spacing?

2020-12-10 18:35 UTC, aaronshekey commented
The organization / naming of this is a little weird. This is the first component we have that also has atomic classes of the same name. There's a `List` page in both the base classes and components 🤔 

Would calling this something like separators make sense? It's mildly weird that this component only has the horizontal modifier. Would we move all list styling over here? Or can this be a tiny component within our base styles. This one has got me thinking too much.

Additionally, on the core side of things I haven't quite found any examples of these separators. We've gotten rid of lots of `|` throughout the product, instead opting for simple white space and font color changes. Should we get with @PiperLawson to consider alternate treatments?
![image](https://user-images.githubusercontent.com/1369864/101814581-f528a180-3ae3-11eb-9001-ca84f3de9d8f.png)

Sometimes the best component is no component.

2020-12-10 18:58 UTC, benjamin-hodgson commented on lib/css/components/_stacks-lists.less
> +        content: '•';
I don't recommend using Unicode in code. This is liable to behave unpredictably depending on whatever default encoding the useragent has. Stick with the `\u` literal

2021-05-03 19:16 UTC, aaronshekey requested changes
As discussed in Slack, I'm taking the official stance that instead of horizontal lists with bulleted dividers, we should be using white space instead. This doesn't need to be a component, and we should shy away from this Talent-only aesthetic moving forward.

2021-05-03 19:17 UTC, aaronshekey commented
Closing in favor of whitespace-only in our horizontal lists. 😞

2021-05-03 19:17 UTC, closed without merging