Add focus-visible polyfill
StackExchange/Stacks pull request #575
Opened 2021-01-04 21:56 UTC by aaronshekey

This PR explores adding the https://github.com/WICG/focus-visible polyfill, and swaps our approach to button focus. This _should_ allow us to switch to using focus-visible instead of focus, meaning focus states are only added when using keyboard navigation.

2021-01-05 20:12 UTC, bnickel commented
This looks good overall and is a welcome improvement.  One bug I spotted is that `.s-btn.s-btn__muted.s-btn__filled` loses its focus style in dark mode.  Just your average selector priority and sequence battles.

2021-01-05 22:24 UTC, aaronshekey commented
> Just your average selector priority and sequence battles.

Good looking out! I caught all those in light mode.

This is a result of our stock button being super weird and not having borders.

2021-01-06 15:50 UTC, aaronshekey commented
@b-kelly Any reservations in using this polyfill and including it in our JS?

2021-01-06 16:01 UTC, b-kelly commented
I'll take a look at this today. Thanks for the reminder!

2021-01-07 01:30 UTC, b-kelly requested changes
Taking a quick peek at the source code for `focus-visible`, it adds a handful of document listeners, including binding then unbinding bunch of mouse listeners on page load. I'm a little skeptical of adding a bunch of js overhead to every page load. I'm pumping the brakes on this for now until I can do some additional review/testing to see what our tradeoffs are.

2021-01-08 18:02 UTC, bnickel requested changes
I'd like to add the actual selector so it's not a huge regression for people who consume the CSS and not the JS.

Also, could we package focus styles for `.s-navigation--item` in this PR or should that be its own thing after this ships?

2021-01-08 18:02 UTC, bnickel commented on lib/css/exports/_stacks-mixins.less
> +}
```suggestion

    &:focus-visible {
        outline: none;
        @rules();
    }
}
```

Since Chrome supports this and Firefox is on the way, should we include actual support for the selector?

2021-01-08 18:02 UTC, bnickel commented on lib/css/exports/_stacks-mixins.less
> +.focus(@rules) {
Should this be `focus-visible` or some variant thereof? `focus` already has its own different meaning.

2021-01-08 18:16 UTC, b-kelly commented on lib/css/exports/_stacks-mixins.less
> +}
+1. [caniuse](https://caniuse.com/css-focus-visible) reports that Safari is the last holdout (Edge legacy too, I guess). Maybe we can figure out a progressive enhancement scenario for those two?

2021-01-08 18:31 UTC, aaronshekey commented
I'll just roll with proper `:focus-visible` styles and leaving off the focus-visible polyfill. It won't be perfect for those browser that don't support it, but it'll be better than showing focus styling on click.

2021-01-08 18:31 UTC, closed without merging