Add anchor underline to high contrast
StackExchange/Stacks pull request #769
Opened 2021-10-06 19:23 UTC by dancormier

Upstream changes to support https://github.com/StackEng/StackOverflow/pull/9535

Only merge once https://github.com/StackEng/StackOverflow/pull/9535 and https://github.com/StackEng/StackOverflow/pull/9526 are merged.

2021-10-06 21:20 UTC, aaronshekey commented on lib/css/base/_stacks-reset-normalize.less
> +  .highcontrast-mode({ text-decoration: underline; });
Let's do this in `stacks-links.less` instead: https://github.com/StackExchange/Stacks/blob/develop/lib/css/components/_stacks-links.less#L17

There's a future where we kill these resets entirely #609

2021-10-06 22:26 UTC, dancormier commented on lib/css/base/_stacks-reset-normalize.less
> +  .highcontrast-mode({ text-decoration: underline; });
Good call. I knew it was wrong when I was doing it and I did it anyway. 🤷‍♂️

2021-10-19 18:25 UTC, aaronshekey requested changes
Just 2 teeny tiny bits. Merge whenever you'd like into production SO. That work can definitely ship before the next release of Stacks.

We've got a blue that's a little leaky in the case of `s-card`. 
<img width="320" alt="image" src="https://user-images.githubusercontent.com/1369864/137968582-ad0f08bd-4a53-40a7-9078-f85b72b42a96.png">

2021-10-19 18:25 UTC, aaronshekey commented on lib/css/base/_stacks-reset-normalize.less
> + * 3. Adds underline to links in high contrast
```suggestion
```

2021-11-08 15:06 UTC, aaronshekey approved these changes

2021-11-08 15:48 UTC, merged