Remove the static config
StackExchange/Stacks pull request #892
Opened 2022-03-30 17:45 UTC by dancormier

This PR removes `lib/css/base/_stacks-configuration-static.less`, and moves necessary Less variables (`@css-reset`, `@breakpoints`) to `lib/css/exports/_stacks-constants-helpers.less`.

I've yet to test this against core so standby.

---

See also:

![PR comment saying "we're coming for you next #stacks-config-static"](https://user-images.githubusercontent.com/647177/160898122-a9227682-1237-4283-8057-772cda90cf85.png)

2022-04-05 19:02 UTC, aaronshekey commented on lib/css/stacks-static.less
>  @import "base/configuration-static.less";
I think this one's gotta go yet.

2022-04-05 19:03 UTC, dancormier commented on lib/css/stacks-static.less
>  @import "base/configuration-static.less";
Ah, damn funky merge. Removed!

2022-04-05 20:22 UTC, aaronshekey approved these changes

2022-04-06 18:34 UTC, b-kelly requested changes
Looks like we've lost the ability to set css resets and multiple breakpoints - both of which we're using in prod. I'm going to see if I can come up with a good solution here.

2022-04-06 18:47 UTC, dancormier commented
> Looks like we've lost the ability to set css resets and multiple breakpoints - both of which we're using in prod. I'm going to see if I can come up with a good solution here.

Is the reset not handled throught `lib/css/base/reset.less`?

```
// the default CSS reset is normalize.css; other possibilities are the Eric Meyer reset, and no reset at all.

#stacks-internals() {
    #include-css-reset(meyer) {
        @import "_stacks-reset-meyer.less";
    }
    #include-css-reset(normalize) {
        @import "_stacks-reset-normalize.less";
    }
    /* stylelint-disable block-no-empty */
    #include-css-reset(none) {
    }
    /* stylelint-enable */
}

& {
    #stacks-internals #load-static-config();
    #stacks-internals #include-css-reset(@css-reset);
}
```

2022-04-06 19:20 UTC, b-kelly commented
@dancormier Unfortunately, no. I just double checked and downstream consumers aren't setting this value with the current syntax. Working on a downstream fix now to see if we need to make any changes here.

2022-04-07 18:57 UTC, b-kelly commented
I'm starting to think we can't merge this without an overhaul on how we deliver breakpoints and resets. Any concerns on leaving this for 2.0?

2022-04-07 19:22 UTC, dancormier commented
> I'm starting to think we can't merge this without an overhaul on how we deliver breakpoints and resets. Any concerns on leaving this for 2.0?

Yep, sounds good.

2022-04-07 19:22 UTC, closed without merging